DEFAULT_ROAST_PROMPT = "I want you to roast my CV hard! Go all out with humor and wit, making it as entertaining as possible. 
                Focus on the flaws and ridiculousness without holding back. Just make it funny and engaging, 
                and don't hold back on the creativity! Don't make it too long and go straight to the roast. If it doesn't look like a CV, return 'false'"

MOCK_ROAST_MESSAGE = {
  "roast": {
      "id": 9,
      "user_id": 1,
      "blob_id": 16,
      "text": "Sure thing! Here comes the roast of your CV!\n\n---\n\n**WELCOME TO ISAC ARVIDSSON ROSENBERG’S CV CIRCUS!**\n\n**PERSONAL INFORMATION:**\nAh, first things first: Did you call your parents and tell them you’re still using “Arvidsson” instead of “Superstar Developer”? That’s a missed branding opportunity right there!\n\n**INTRODUCTION:**\nYou’re a “highly motivated and cheerful individual”? What’s next, declaring that you “love long walks on the beach”? This isn’t a dating profile! You want an internship, not to join a book club. And let’s be honest—your “meticulous attention to detail” is probably an interesting way of saying you still use Comic Sans in your cover letters.\n\n**EDUCATION:**\n“Fullstack web development with .NET”? You know that’s like signing up for a cooking class and only learning how to microwave popcorn, right? But hey, at least you tried to diversify with your Harvard class—nothing says “I'm serious” like free online courses!\n\n**WORK EXPERIENCE:**\n- **FULL STACK DEVELOPMENT INTERNSHIP**: Oh, look at you—“responsible for maintenance and expanding an internal CMS system written in React”! I’m guessing this is where the “internal” part becomes very real—you couldn’t quite escape into a real job yet, huh?\n  \n- **PROJECT MANAGEMENT**: Managing a family landscaping business? Are you sure you didn’t just dig up your garden for practice? And what’s the deal with your “climbing gym project”? Sounds like the perfect metaphor for your career path—climbing a wall only to realize it's not even a real job!\n\n- **BAR AND RESTAURANT MANAGEMENT**: “Best western \u0026bar in Vietnam”? Are we sure that’s not a Facebook group you created for your friends? I’m envisioning you telling customers, “Our Wi-Fi password is ‘please don’t leave’” as the food flies off the table.\n\n**ADDITIONAL SKILLS:**\n- **Azure, AWS, Python**: Wow, you’re well-versed in cloud technology! Too bad your career is grounded in the earthiness of restaurant management. Is there a cloud service for “getting my life together”?\n\n**FINAL COMMENTARY:**\nThis CV screams “I am versatile!” but honestly, it might be more accurate to say, “I’m indecisive and still haven’t figured out what I want to be when I grow up.” But don’t worry, Isac! We all start somewhere, and in this epic game of employment hide-and-seek, you’ll just have to keep running in circles until you find the right hiding spot!\n\n---\n\nThere you have it! A roast as spicy as your ambitions!",
      "created_at": "2024-11-08T16:18:25.124Z",
      "updated_at": "2024-11-08T16:18:25.124Z",
      "img_url": "http://localhost:3001/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eaa48ff3817067b598a497a10d9310089dad6e97/cv_image.jpg"
  }
}